### ISSUE TITLE
the random teacher 0th performance

### ISSUE THREAD

**Issue by WANGSSSSSSS** [liuxingbin/dbot#1]
![image](https://user-images.githubusercontent.com/50823578/200210387-14811caa-2784-4f99-9a0b-fb2939068eb5.png)
hi, i am confused about the random teacher 0th performance. intuitively speaking, a model with random weights will not exhibit a reasonable performance.  so i want to know whether there are some technology applied to this teacher.

**Comment by liuxingbin** [comment]
The performance here is Top-1 accuracy after fine-tuning, as well as the other four entries.
