### ISSUE TITLE
The settings in downstream tasks

### ISSUE THREAD

**Issue by JiahuiChen-GitHub** [liuxingbin/dbot#2]
Hi, I notice that the settings for object detection are not consistant in your paper and in this repo.  
For ViT-Base model, the setting in your paper is {cascade-maskrcnn; epoch:1x; layerdecay: 0.75}, while the setting in this repo is  {cascade-maskrcnn; epoch:3x; layerdecay: 0.65}. So I want to know which setting should we use to reproduce your work.

**Comment by liuxingbin** [comment]
see here:  https://github.com/liuxingbin/dbot/blob/main/DOWNSTREAM.md#object-detection-and-instance-segmentation-on-coco
