### ISSUE TITLE
Minimum Hardware Requirements

### ISSUE THREAD

**Issue by hiroalchem** [liuxingbin/dbot#3]
I am new to self-supervised learning, what is the minimum hardware required to use dBOT? Is it possible to learn with my own dataset on a single GPU?

**Comment by liuxingbin** [comment]
It is not possible to train dBOT with a single GPU. See table11 in our paper for detail. However, downstream research will be possible. Feel free to play with our pre-trained models.

**Comment by hiroalchem** [comment]
@liuxingbin Thank you for your reply. 
I wanted to apply this to a somewhat specific original dataset, so I would like to do the pre-train itself if possible, but was I correct in understanding that this is not possible because it cannot be trained in a realistic time on a single GPU? Would it be possible to work on this with a few GPUs with a bit lower performance? Or is it that the batch size would be too small for learning to work? The dataset size is quite small compared to ImageNet.

**Comment by liuxingbin** [comment]
You can try to train your specific data and see how long it would take for one epoch. You can set batch_size and accum_iter to maintain the effective_batch_size (see [here](https://github.com/liuxingbin/dbot/blob/main/PRETRAIN.md#pre-training-dbot)). We have not tested our dBOT on a few GPUs, but it should achieve the same results as long as you keep the effective_batch_size with the original setting.

**Comment by hiroalchem** [comment]
I will try it once I can. Thank you very much for your kind advice.
