### ISSUE TITLE
Code for averaged attention distance and SVD

### ISSUE THREAD

**Issue by yuchongy1** [liuxingbin/dbot#4]
Hi Authors,

Thanks for your work.

Could we have the code for the property analysis described in the paper as well (i.e., averaged attention distance and SVD).

**Comment by liuxingbin** [comment]
Thanks for your interest. Currently, I am in a rebuttal period. We will release the code soon.  I'm closing this as a result -- if we find anything notable I'll post it here.

**Comment by liuxingbin** [comment]
We release the code for average attention distance and svd. 
Please see [HERE](https://github.com/liuxingbin/dbot/tree/main/analysis).
