### ISSUE TITLE
the pretrain data for the experiment of data-richer teacher

### ISSUE THREAD

**Issue by smarengin** [liuxingbin/dbot#5]
Hi, Authors，
Thank you for your good work!
I want to know when you distill from the data-richer teacher, what is the data you use, IN1K or IN1K+400M ITp?
I see in your table 8, you say you use IN1K+400M ITp, so I wonder if the good performance is due to the rich data, not the method. I suppose here you want to show the data of teacher, not the student, is that true?
Thanks!

**Comment by liuxingbin** [comment]
Yes, you are right. 
The pre-training data here is the data of teacher. 
We use CLIP (pretarined with IN1K+400M ITp.) to distill our ViT only with IN1K.

**Comment by smarengin** [comment]
Thank you for your reply!
